spring.application.name=release-pilot

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/releasepilot}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:releasepilot}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:releasepilot}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
